Endret fra "snake_case" til "camelCase" med Alexander Dorfman.
bjerkio/abax-node-sdk pull request #78
Opened 2024-02-08 11:58 UTC by Tigua002

2024-02-08 12:23 UTC, Xillians commented on package-lock.json
Denne filen burde kanskje ikke være med, dette prosjektet bruker vanligvis `pnpm`

2024-02-08 12:23 UTC, Xillians commented on src/abax-client.ts
> +            query: { tripIds: tripIds },
```suggestion
            query: {  tripIds },
```

2024-02-08 12:23 UTC, Xillians commented on src/authentication/decode-abax-profile.ts
>    idp: z.string(),
disse to ser ut til å kanskje være best med snake_case

2024-02-08 12:23 UTC, Xillians commented on src/authentication/decode-abax-profile.ts
> +  phoneNumber: z.string().optional(),
disse to ser ut til å kanskje være best med snake_case

2024-02-08 12:33 UTC, Xillians commented on src/calls/get-odometer-values.ts
> +  tripFinish: odometerReadingSchema.optional(),
```suggestion
  tripFinish: odometerReadingSchema.optional(),
  tripStart: odometerReadingSchema.optional(),
```

2024-02-08 12:34 UTC, Xillians approved these changes

2024-02-08 12:40 UTC, braaar commented on src/abax-client.ts
> +        ({ input: { vehicleId: vehicleId } }) =>
```suggestion
        ({ input: { vehicleId } }) =>
```

2024-02-08 12:41 UTC, braaar commented on src/abax-client.ts
> +            dateTo: dateTo,
```suggestion
            pageSize,
            dateFrom,
            dateTo,
```

2024-02-08 12:41 UTC, braaar commented on src/abax-client.ts
> +            query: { tripIds: tripIds },
```suggestion
            query: { tripIds },
```

2024-02-08 12:44 UTC, braaar commented on src/authentication/__tests__/abax-auth.test.ts
> +        refreshToken: 'refresh_token',
This change should be reverted. This is an intercept/mock of the actual Abax API, which does reply with the data in this shape.

2024-02-08 12:44 UTC, braaar commented on src/authentication/__tests__/abax-auth.test.ts
> +        refreshToken: 'new_refresh_token',
This change should be reverted. This is an intercept/mock of the actual Abax API, which does reply with the data in this shape.

2024-02-08 12:48 UTC, braaar commented on src/authentication/calls.ts
> +    refreshToken: z.string().optional(),
This won't work. This schema is used to parse the reply from the API, where the fields are in snake case. In order to get camel cased data out of this, we need to use `.transform()`. See example below.

2024-02-08 12:49 UTC, braaar commented on src/calls/get-equipment.ts
>  });
We need to transform the data after parsing, like so: 

```suggestion
  unit_driven: z.boolean(),
}).transform(({unit_driven}) => ({unitDriven: unit_driven}));
```

This applies to every zod schema.

2024-02-09 09:24 UTC, braaar commented on src/authentication/decode-abax-profile.ts
> +})
The return value of the tranform function is what is returned when parsing data with this schema. We want all the data here, not just these four fields. This applies to many other examples throughout this PR.

2024-02-09 12:24 UTC, braaar requested changes
Left out a few things, but this is looking good!

2024-02-09 12:24 UTC, braaar commented on src/authentication/__tests__/abax-auth.test.ts
> +        "expiresAt": 2000-02-01T13:00:00.000Z,
```suggestion
        "expiresAt": 2000-02-01T14:00:00.000Z,
```

2024-02-09 12:24 UTC, braaar commented on src/authentication/__tests__/abax-auth.test.ts
> +        "expiresAt": 2000-02-01T13:00:00.000Z,
```suggestion
        "expiresAt": 2000-02-01T14:00:00.000Z,
```

2024-02-09 12:24 UTC, braaar commented on src/calls/list-trips.ts
> +}))
```suggestion
}).transform(({ signal_source, accuracy_radius, ...data }) => ({
  ...data,
  signalSource: signal_source,
  accuracyRadius: accuracy_radius
}))
```

2024-02-09 12:24 UTC, braaar commented on src/calls/list-trips.ts
> +}))
Here the `vehicle` field, which is an object, has a field in snake case, so that object must also be transformed.

2024-02-09 12:24 UTC, braaar commented on src/calls/list-usage-summary.ts
>  export const listUsageSummaryResponseSchema = z.object({
This schema should also be converted to camelCase. It's currently in PascalCase.

2024-02-09 12:24 UTC, braaar commented on src/calls/list-vehicles.ts
> +}))
```suggestion
}).transform(data => ({
  number: data.number, 
  registrationDate: data.registration_date
}))
```

2024-02-09 12:24 UTC, braaar commented on src/calls/list-vehicles.ts
> +}))
```suggestion
}).transform(({ serial_number, ...data }) => ({
  ...data,
  serialNumber: serial_number
}))
```

2024-02-09 12:24 UTC, braaar commented on src/calls/list-vehicles.ts
> +}))
```suggestion
}).transform(({ in_movement, signal_source, accuracy_radius, ...data => ({
  ...data,
  inMovement: data.in_movement,
  signalSource: data.signal_source,
  accuracyRadius: data.accuracy_radius
}))
```

This schema should be moved to the `shared.ts` file and reused in `list-vehicles.ts` and `get-equipment.ts`

2024-02-09 12:24 UTC, braaar commented on src/calls/list-vehicles.ts
> +}))
```suggestion
}).transform(({license_plate, commercial_class, registered_at, fuel_type, engine_size, co2_emissions, ...data}) => ({
  ...data,
  licensePlate: license_plate,
  commercialClass: commercial_class,
  registeredAt: registered_at,
  fuelType: fuel_type,
  engineSize: engine_size,
  co2Emissions: co2_emissions,
}))
```

2024-05-30 11:49 UTC, closed without merging